# Cloud Build config for SAS Query Generator Streamlit UI
# Trigger: Push to main with changes in sas_generator/app.py or Dockerfile-sas-generator-ui
#
# Required substitutions (set in trigger or via --substitutions):
#   _REGION: Cloud Run region (default: us-central1)
#
# Prerequisites:
#   - sas-generator-api must be deployed first
#   - IAM binding must be configured for service-to-service auth

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: sas-query-generator
  _API_SERVICE_NAME: sas-generator-api

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile-sas-generator-ui'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Get SAS Generator API URL
        SAS_API_URL=$(gcloud run services describe ${_API_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')

        gcloud run deploy ${_SERVICE_NAME} \
          --image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --labels=team=ai-agents \
          --memory=1Gi \
          --cpu=1 \
          --timeout=3600 \
          --concurrency=80 \
          --max-instances=10 \
          --min-instances=0 \
          --session-affinity \
          --cpu-boost \
          --set-env-vars="SAS_API_URL=$${SAS_API_URL}" \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=$PROJECT_ID"

  # Create GitHub deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y jq

        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} --region=${_REGION} --format='value(status.url)')

        DEPLOY_RESPONSE=$(curl -s -X POST \
          -H "Authorization: token $$GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${REPO_FULL_NAME}/deployments \
          -d '{"ref":"'$COMMIT_SHA'","environment":"sas-generator-ui","auto_merge":false,"required_contexts":[]}')

        echo "Deploy response: $$DEPLOY_RESPONSE"
        DEPLOY_ID=$(echo "$$DEPLOY_RESPONSE" | jq -r '.id')
        echo "Deploy ID: $$DEPLOY_ID"

        curl -s -X POST \
          -H "Authorization: token $$GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${REPO_FULL_NAME}/deployments/$${DEPLOY_ID}/statuses \
          -d '{"state":"success","environment_url":"'$${SERVICE_URL}'","description":"Deployed to Cloud Run"}'
    secretEnv: ['GITHUB_TOKEN']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GITHUB_TOKEN/versions/latest
      env: 'GITHUB_TOKEN'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
